kumuluzee:
  name: catalogue-service
  env:
    name: dev
  version: 1.0.0
  server:
    http:
      port: 8082
  datasources:
  - jndi-name: jdbc/SharyCarDB
    connection-url: jdbc:postgresql://sharycardb.czqdzv4vbdko.eu-west-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: postgres
    max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/SharyCarDB
  discovery:
    etcd:
      hosts: http://etcd:2379
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://etcd:2379
      
rest-config:
  payment-currency: EUR
  reservation-value: 5